blank_issues_enabled: false
contact_links:
  - name: Airheads Developer Community
    url: https://community.arubanetworks.com/community-home/digestviewer?communitykey=ea467413-8db4-4c49-b5f8-1a12f193e959&tab=digestviewer
    about: Please ask and answer questions here.
